#!/usr/bin/env bash

function waitForService() {
  echo -e "\n"
  echo "Waiting $1 to launch on $2"

  while ! nc -z localhost "$2" &> /dev/null; do
      sleep 0.1
      echo -n "."
  done
  echo ""
  echo "$2 is up ✅"
  echo -e "\n"
}
