#!/usr/bin/env bash
set -eo pipefail

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# shellcheck source=./functions/*
for file in "$SCRIPT_DIR"/functions/*; do source "$file"; done

trap cleanUp TERM EXIT
headed=false

if [ "$1" != "" ]
then
  case $1 in
    -h | --headed )
        headed=true
        ;;
    *)
        echo "Invalid option: $1"
        exit
       ;;
  esac
fi

echo "Linting..."
(cd ui && yarn lint &> /dev/null &)
(cd journey && yarn lint &> /dev/null &)

(cd ui && yarn test)

(
 cd ui && yarn dev &> /dev/null &
 waitForService ui 3000
)

(
 cd journey
 if [ $headed = true ]
 then
    yarn test:headed
  else
    yarn test
 fi

)

cleanUp
