#!/usr/bin/env bash
set -eo pipefail

DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$DIR"/functions

trap cleanUp TERM EXIT
headed=false

if [ "$1" != "" ]
then
  case $1 in
    -h | --headed )
        headed=true
        ;;
    *)
        echo "Invalid option: $1"
        exit
       ;;
  esac
fi

echo "Linting..."
(rcd ui && yarn lint &> /dev/null &)
(rcd journey && yarn lint &> /dev/null &)

(rcd ui && yarn test)

(
 rcd ui && yarn start &> /dev/null &
 waitForService ui 3000
)

(
 rcd api && yarn start &> /dev/null &
 waitForService ui 4000
)

(
 echo -e "\n"
 rcd journey
 if [ $headed = true ]
 then
    yarn test:headed
  else
    yarn test
 fi

)

cleanUp
